### ISSUE TITLE
state of art -> ox-linguistics

### ISSUE THREAD

**Issue by OrionRandD** [wyleyr/ox-linguistics#1]
Hi,
Wyleyr,
Looking at the time you last commited changes,
Is this package still in development?
Seems a very interesting tool.
If not. Why did you stopped?
That would be a very good MELPA package
For people interested in learning linguistics.

Do you also know this package?
https://github.com/andcarnivorous/linguistic
Thx a lot

**Comment by wyleyr** [comment]
Sorry for the extremely late reply! No, the package is not in active development at the moment, but I'm happy to consider patches/PRs for improvements.
